framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

        # Load validation rules from YAML files (hexagonal approach)
        mapping:
            paths:
                - '%kernel.project_dir%/config/validator'

when@test:
    framework:
        validation:
            not_compromised_password: false
